<?php
 $MIZHI =  array (
  'title' => 'MizhiPlayer觅知弹幕ART播放器',
  'keywords' => '觅知ART专业版可对接JSON解析弹幕播放器',
  'title_url' => 'https://www.98dou.cn',
  'logo' => './img/logo.png',
  'color' => '#ff0000',
  'waittime' => '5',
  'right_text' => 'MizhiPlayer弹幕ART播放器',
  'right_link' => 'https://98dou.cn/',
  'err_bg' => 'img',
  'err_bg_imgurl' => './img/bg.jpg',
  'err_bg_vodurl' => 'https://static.ws.126.net/163/f2e/news/mp_pc_login/resource/media/part1.15d54737.mp4',
  'showtime' => 'on',
  'video_thumbnails' => 'on',
  'beisu' => 'on',
  'api_ur_1' => '',
  'api_xl_url' => '',
  'api_ur_3' => '',
  'api_ur_4' => '',
  'api_ur_5' => '',
  'api_zyurl_domain_all' => 'cdnlz13.com|cdnlz13.com|cdnlz22.com|ffzy-online5.com',
  'api_zyurl_1' => '',
  'api_zyurl_domain_1' => 'cdnlz13.com|cdnlz13.com|cdnlz22.com',
  'api_zyurl_2' => '',
  'api_zyurl_domain_2' => 'ffzy-online5.com',
  'api_zyurl_3' => '',
  'api_zyurl_domain_3' => '',
  'api_zyurl_4' => '',
  'api_zyurl_domain_4' => '',
  'api_zyurl_5' => '',
  'api_zyurl_domain_5' => '',
  'load_bg' => './img/pic_bj.avif',
  'errzdytext' => '自定义文字',
  'errzdylink' => '自定义链接',
  'blank_referer' => 'on',
  'fdhost' => '123.com|456.com',
  'ads' => 
  array (
    'pause' => 
    array (
      'pic' => './img/loading.gif',
      'link' => 'https://www.98dou.cn/4973.html',
    ),
  ),
  'pmdzdy' => '<strong><font face="楷体_GB2312" color="#ff0000" size="5">◆温馨警告:请自行辨别视频中的广告，以免上当受骗◆ 本站视频均来源于第三方，视频中出现任何广告及内容均与本站无关！请自行辨别！切勿轻信！</font> <font face="楷体_GB2312" color="#0fb4ee" size="5">请文明发弹幕，营造一个和谐的观影氛围</font></strong>',
  'pmdtopweizhi' => '10%',
  'pmdloopnum' => '3',
  'pmdspeed' => '8',
  'tsmsg' => '解析成功：请勿随意相信视频中的</br>广告、网址、电话、二维码等！',
  'tstime' => '8000',
  'yiyanhitokoto' => 'on',
  'content' => '如果你的梦想,是拯救苍生,那我的梦想,便唯你一人。',
  'content2' => '全网影迷聚集地,看视频就用-MizhiPlayer觅知弹幕ART播放器',
  'danmuon' => 'on',
  'dm_url_md5' => 'on',
  'danmuku' => './dmku/',
  'dm_url_canshu' => '?ac=dm&id=',
  'sendtime' => '500',
  'dmrule' => './dmku/dm_rule.html',
  'pbgjz' => '操ABCDEFGHIJKLMNOPQRSTUVWSYZabcdefghijklmnopqrstuvwsyz艹',
  'dm_speed' => '10',
  'dm_fontSize' => '22',
  'dm_margin_1' => '10',
  'dm_margin_2' => '80%',
);
?>